# Generated by Django 3.1.7 on 2021-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliyun_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='云名称')),
                ('login', models.URLField(max_length=60, null=True, verbose_name='登录地址')),
                ('type', models.CharField(max_length=60, null=True, verbose_name='备注')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='绑定手机')),
                ('account_number', models.CharField(max_length=30, null=True, verbose_name='账号')),
                ('password', models.CharField(max_length=30, null=True, verbose_name='密码')),
            ],
            options={
                'verbose_name': '阿里云账号密码',
            },
        ),
    ]
